apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  selector:
    app: fastapi
  ports:
    - protocol: TCP
      port: 80  # Puerto externo
      targetPort: 8080  # Puerto dentro del contenedor
  type: NodePort  # Cambiar a LoadBalancer para GKE
